### ISSUE TITLE
CSRF Token Is Missing

### ISSUE THREAD

**Issue by abheekda1** [CQCumbers/scibowldb#1]
Hey! I think this is a really cool API to use, but while testing it out I came across the issue that, while submitting a POST request with curl, I would get an error 400, can the page would say CSRF token missing.

Expected Behavior:
Returns random question with a category filter.

Please let me know if I'm doing something wrong!

Edit: I would just like to add on that the `/api/questions` endpoint seems to be non-functioning entirely, with a GET request to it resulting in an error 500.

**Comment by CQCumbers** [comment]
Apologies for the delayed response. Both of these issues should be fixed by https://github.com/CQCumbers/scibowldb/commit/336af24f7db0d0cf49fcd441e1b5fabb82762e3f. Let me know if there are further issues.

**Comment by abheekda1** [comment]
That's awesome! Thanks so much!
